<%@ Page Title="" Language="C#" MasterPageFile="~/MiMaster.Master" AutoEventWireup="true" CodeBehind="Legal.aspx.cs" Inherits="Ejemplo1.Legal" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <section>
        <h1>Información legal</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut gravida et sapien ut pulvinar. Sed nec nibh mattis lacus accumsan laoreet. Quisque at ante leo. Quisque laoreet placerat pharetra. Morbi accumsan lacus sed facilisis mattis. Duis nec arcu non quam pretium vehicula. Mauris sit amet neque in odio tincidunt ullamcorper nec a erat. Cras volutpat justo nec velit pharetra tincidunt. Vestibulum id tempor nibh. Suspendisse nec varius nisi. Sed fermentum tempor quam eu accumsan. Maecenas quis metus id diam congue egestas. Sed facilisis vel libero malesuada finibus.</p>
        <p>Morbi at risus lacus. Nam dolor ligula, porta eu ultrices sit amet, bibendum nec eros. Pellentesque iaculis augue arcu, vitae blandit leo luctus vel. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam aliquet sit amet felis ac pretium. Praesent non ullamcorper urna. In pharetra vestibulum tempus. Donec sed semper mi, at euismod mauris. Cras eleifend lacinia finibus. Curabitur dictum consectetur mauris vel fermentum. Donec rhoncus vehicula eros. Proin et tempor enim, id maximus ex.</p>
        <p>Donec maximus ornare diam quis imperdiet. Nam viverra ligula arcu, id fringilla libero lobortis vitae. Vestibulum eget massa quis augue tristique cursus eget quis erat. Suspendisse ornare nulla vel erat facilisis, rhoncus gravida eros sodales. Suspendisse volutpat, justo vitae lobortis tincidunt, sem leo hendrerit sem, in vestibulum tortor purus at ipsum. Nulla a nibh lectus. In eu turpis mattis, bibendum est et, egestas mauris. Nullam tempus, dolor vitae vulputate condimentum, mi odio tristique velit, a accumsan nisl justo ac mi.</p>
        <p>Sed pretium, nisl sit amet venenatis pulvinar, sapien nisl luctus nisi, eu consequat elit dolor ut ex. Nullam sed vulputate est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque ultricies erat elit, eu commodo nisl elementum quis. Cras eu egestas neque. Donec viverra posuere mauris sed efficitur. Duis arcu enim, porttitor sit amet magna id, tristique imperdiet erat. Nullam pharetra ex nec lorem ullamcorper mattis. Donec condimentum a neque id egestas. In nisi eros, vestibulum eget ante a, ultricies sollicitudin neque. Ut diam libero, aliquet non tortor sed, fermentum mollis elit. Duis id accumsan metus.</p>
        <p>Etiam auctor vulputate dapibus. Etiam non venenatis nunc. Nullam facilisis eget ante sed pretium. Quisque magna felis, interdum sit amet risus nec, vulputate aliquet nisl. Praesent porta at mi vitae maximus. Sed consequat nisl sit amet volutpat mattis. Aliquam sit amet lacinia nibh. Quisque sed sapien malesuada, sollicitudin nisi a, aliquam odio. Quisque semper, nisi et cursus venenatis, nibh erat pellentesque mi, vel commodo mauris augue vitae sapien. Phasellus pharetra, lectus et bibendum fermentum, nisi est lobortis justo, in convallis nisl ex eu sem. Quisque vestibulum nisl nec diam laoreet varius.</p>
    </section>
</asp:Content>
